// <auto-generated />
using System;
using GraduateAppTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraduateAppTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609192007_AddAnnouncementDateAndQuota")]
    partial class AddAnnouncementDateAndQuota
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GraduateAppTracker.Models.UniversityProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AnnouncementDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("MinAlesScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("MinLanguageScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("Quota")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresLanguage")
                        .HasColumnType("bit");

                    b.Property<string>("UniversityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("UniversityPrograms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationDate = new DateTime(2026, 6, 23, 22, 20, 6, 781, DateTimeKind.Local).AddTicks(8690),
                            CreatedAt = new DateTime(2026, 6, 9, 22, 20, 6, 781, DateTimeKind.Local).AddTicks(8698),
                            DepartmentName = "Bilgisayar Mühendisliği",
                            MinAlesScore = 70m,
                            MinLanguageScore = 65m,
                            RequiresLanguage = true,
                            UniversityName = "Ankara Üniversitesi"
                        },
                        new
                        {
                            Id = 2,
                            ApplicationDate = new DateTime(2026, 6, 14, 22, 20, 6, 781, DateTimeKind.Local).AddTicks(8700),
                            CreatedAt = new DateTime(2026, 6, 9, 22, 20, 6, 781, DateTimeKind.Local).AddTicks(8700),
                            DepartmentName = "Yapay Zeka ve Veri Mühendisliği",
                            MinAlesScore = 75m,
                            RequiresLanguage = false,
                            UniversityName = "İstanbul Teknik Üniversitesi"
                        },
                        new
                        {
                            Id = 3,
                            ApplicationDate = new DateTime(2026, 7, 9, 22, 20, 6, 781, DateTimeKind.Local).AddTicks(8702),
                            CreatedAt = new DateTime(2026, 6, 9, 22, 20, 6, 781, DateTimeKind.Local).AddTicks(8703),
                            DepartmentName = "Elektrik-Elektronik Mühendisliği",
                            MinAlesScore = 80m,
                            MinLanguageScore = 70m,
                            RequiresLanguage = true,
                            UniversityName = "ODTÜ"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
