// <auto-generated />
using System;
using GraduateAppTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraduateAppTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GraduateAppTracker.Models.UniversityProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("MinAlesScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("MinLanguageScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("RequiresLanguage")
                        .HasColumnType("bit");

                    b.Property<string>("UniversityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("UniversityPrograms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationDate = new DateTime(2026, 6, 23, 21, 19, 7, 413, DateTimeKind.Local).AddTicks(7565),
                            CreatedAt = new DateTime(2026, 6, 9, 21, 19, 7, 413, DateTimeKind.Local).AddTicks(7573),
                            DepartmentName = "Bilgisayar Mühendisliği",
                            MinAlesScore = 70m,
                            MinLanguageScore = 65m,
                            RequiresLanguage = true,
                            UniversityName = "Ankara Üniversitesi"
                        },
                        new
                        {
                            Id = 2,
                            ApplicationDate = new DateTime(2026, 6, 14, 21, 19, 7, 413, DateTimeKind.Local).AddTicks(7577),
                            CreatedAt = new DateTime(2026, 6, 9, 21, 19, 7, 413, DateTimeKind.Local).AddTicks(7578),
                            DepartmentName = "Yapay Zeka ve Veri Mühendisliği",
                            MinAlesScore = 75m,
                            RequiresLanguage = false,
                            UniversityName = "İstanbul Teknik Üniversitesi"
                        },
                        new
                        {
                            Id = 3,
                            ApplicationDate = new DateTime(2026, 7, 9, 21, 19, 7, 413, DateTimeKind.Local).AddTicks(7581),
                            CreatedAt = new DateTime(2026, 6, 9, 21, 19, 7, 413, DateTimeKind.Local).AddTicks(7582),
                            DepartmentName = "Elektrik-Elektronik Mühendisliği",
                            MinAlesScore = 80m,
                            MinLanguageScore = 70m,
                            RequiresLanguage = true,
                            UniversityName = "ODTÜ"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
